name = "AltSum"
uuid = "30b355e8-99ee-48ba-869c-0489e30a1bfc"
authors = ["André da Silva"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
